polls/urls.py
from django.conf.urls.defaults import *
from django.views.generic import DetailView, ListView
from polls.models import Poll

urlpatterns = patterns('',
    url(r'^$',
        ListView.as_view(
            queryset=Poll.objects.order_by('-pub_date')[:5])),
    url(r'^(?P<pk>\d+)/$',
        DetailView.as_view(
            model=Poll)),
    url(r'^(?P<pk>\d+)/results/$',
        DetailView.as_view(
            model=Poll,
            template_name='polls/poll_results.html'),
        name='poll_results'),
    url(r'^(?P<poll_id>\d+)/vote/$', 'polls.views.vote'),
)

urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template

# Enable admin
from django.contrib import admin
admin.autodiscover()

# Enable static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Enable media
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('',
    # Root (index)
    (r'^$', direct_to_template, {'template': 'index.html'}),

    # Polls app
    url(r'^polls/', include('polls.urls')),
    
    # Admin
    url(r'^admin/', include(admin.site.urls)),
)

# Serve static
urlpatterns += staticfiles_urlpatterns()

# Serve media
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

compile_coffee/models.py
from django.db import models

# Create your models here.

polls/models.py
from django.db import models

import datetime

class Poll(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __unicode__(self):
        return self.question
        
    def was_published_today(self):
        return self.pub_date.date() == datetime.date.today()
    was_published_today.short_description = 'Published today?'

class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice = models.CharField(max_length=200)
    votes = models.IntegerField()
	
    def __unicode__(self):
        return self.choice

compile_coffee/views.py
# Create your views here.

polls/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse

from polls.models import Choice, Poll

def vote(request, poll_id):
    p = get_object_or_404(Poll, pk=poll_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the poll voting form.
        return render_to_response('polls/detail.html', {
            'poll': p,
            'error_message': "You didn't select a choice.",
        }, context_instance=RequestContext(request))
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('poll_results', args=(p.id,)))

polls/templates/polls/base.html
{% extends "base.html" %}

{% block title %}FreddiBlog - Polls{% endblock %}

polls/templates/polls/poll_detail.html
{% extends "polls/base.html" %}

{% block title %}FreddiBlog - Poll detail for {{ poll.question }}{% endblock %}

{% block css %}<link rel="stylesheet" href="{{ STATIC_PREFIX }}css/poll_list.css" type="text/css" media="screen" />{% endblock %}

{% block h1 %}Poll detail for {{ poll.question }}{% endblock %}

{% block content %}
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <form action="/polls/{{ poll.id }}/vote/" method="post">
    {% csrf_token %}
    {% for choice in poll.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
        <label for="choice{{ forloop.counter }}">{{ choice.choice }}</label><br />
    {% endfor %}
    <input type="submit" value="Vote" />
    </form>
{% endblock %}

polls/templates/polls/poll_list.html
{% extends "polls/base.html" %}

{% block title %}FreddiBlog - Poll list{% endblock %}

{% block css %}<link rel="stylesheet" href="{{ STATIC_PREFIX }}css/poll_list.css" type="text/css" media="screen" />{% endblock %}

{% block h1 %}Poll list{% endblock %}

{% block content %}
    {% if poll_list %}
        <ul>
        {% for poll in poll_list %}
            <li><a href="/polls/{{ poll.id }}/">{{ poll.question }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
{% endblock %}

polls/templates/polls/poll_results.html
{% extends "polls/base.html" %}

{% block title %}FreddiBlog - Poll results for {{ poll.question }}{% endblock %}

{% block h1 %}Poll results for {{ poll.question }}{% endblock %}

{% block content %}
    <ul>
    {% for choice in poll.choice_set.all %}
        <li>{{ choice.choice }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>
{% endblock %}

<a href="/polls/{{ poll.id }}/">Vote again?</a>

templates/base.html
<!DOCTYPE html>
<html lang="en" itemscope itemtype="http://schema.org/Blog">
<head>
    <title>{% block title %}FreddiBlog{% endblock %}</title>
    {% load static %}
    {% get_static_prefix as STATIC_PREFIX %}
    <link rel="stylesheet" href="{{ STATIC_PREFIX }}css/base.css" type="text/css" media="screen" />
    {% block css %}{% endblock %}
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_PREFIX }}js/main.js" ></script>
    {% block js %}{% endblock %}
    
    {% comment %}
    {# Removed due to not working on windows? #}
    {% load coffeescript %}
    <script type="text/javascript" src="{{ STATIC_URL}}{% coffeescript "coffee/main.coffee" %}">
    </script>
    {% endcomment %}
    
    <meta itemprop="name" content="FreddiBlog">
    <meta itemprop="description" content="Coffee, code, licorice and punkrawk!">
</head>

<body>
    <header>
        {% block header %}FreddiBlog{% endblock %}
    </header>
    <nav>
        {% block nav %}
        <ul>
            <li><a href="/">Home</a></li>
            <li><a href="/polls/">Polls</a></li>
        </ul>
        {% endblock %}
    </nav>
    <section>
        <h1>{% block h1 %}{% endblock %}</h1>
        {% block content %}{% endblock %}
    </section>
    <footer>
        <g:plusone annotation="inline"></g:plusone>
        {% block footer %}{% endblock %}
    </footer>
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block title %}FreddiBlog - Home{% endblock %}

{% block h1 %}Home{% endblock %}